use crate::emu::emu::Emu;

use super::inst_impl::*;

#[derive(Debug)]
pub enum OperandKind {
    /* implied */                   None,
    /* 8 bit register */            R8,
    /* 16 bit register */           R16,
    /* 8 bit immediate */           Imm8,
    /* 16 bit immediate */          Imm16,
    /* 8 bit register address */    R8_Addr,
    /* 16 bit register address */   R16_Addr,
    /* 8 bit immediate address */   Imm8_Addr,
    /* 16 bit immediate address */  Imm16_Addr,
    Flag_NZ,
    Flag_Z,
    Flag_NC,
    Flag_C,
}

pub struct Instruction(pub OperandKind, pub OperandKind, pub u8, pub fn(emu: &mut Emu, instr: &Instruction, opcode: u8));

pub fn get_instruction(opcode: u8) -> &'static Instruction {
    return &INSTR_INDEX[usize::from(opcode)];
}

// https://gbdev.io/gb-opcodes/optables/
const INSTR_INDEX: [Instruction; 256] =  [
    /* 0x00 NOP          | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_nop),
    /* 0x01 LD BC n16    | - - - - */  Instruction(OperandKind::R16,        OperandKind::Imm16,      3,   opcode_ld),
    /* 0x02 LD [BC] A    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x03 INC BC       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_inc),
    /* 0x04 INC B        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x05 DEC B        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x06 LD B n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x07 RLCA         | 0 0 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_rlca),
    /* 0x08 LD [a16] SP  | - - - - */  Instruction(OperandKind::Imm16_Addr, OperandKind::R16,        5,   opcode_ld),
    /* 0x09 ADD HL BC    | - 0 H C */  Instruction(OperandKind::R16,        OperandKind::R16,        2,   opcode_add),
    /* 0x0A LD A [BC]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x0B DEC BC       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_dec),
    /* 0x0C INC C        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x0D DEC C        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x0E LD C n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x0F RRCA         | 0 0 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_rrca),
    /* 0x10 STOP n8      | - - - - */  Instruction(OperandKind::Imm8,       OperandKind::None,       1,   opcode_stop),
    /* 0x11 LD DE n16    | - - - - */  Instruction(OperandKind::R16,        OperandKind::Imm16,      3,   opcode_ld),
    /* 0x12 LD [DE] A    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x13 INC DE       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_inc),
    /* 0x14 INC D        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x15 DEC D        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x16 LD D n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x17 RLA          | 0 0 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_rla),
    /* 0x18 JR e8        | - - - - */  Instruction(OperandKind::Imm8,       OperandKind::None,       3,   opcode_jr),
    /* 0x19 ADD HL DE    | - 0 H C */  Instruction(OperandKind::R16,        OperandKind::R16,        2,   opcode_add),
    /* 0x1A LD A [DE]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x1B DEC DE       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_dec),
    /* 0x1C INC E        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x1D DEC E        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x1E LD E n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x1F RRA          | 0 0 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_rra),
    /* 0x20 JR NZ e8     | - - - - */  Instruction(OperandKind::Flag_NZ,    OperandKind::Imm8,       3,   opcode_jr),
    /* 0x21 LD HL n16    | - - - - */  Instruction(OperandKind::R16,        OperandKind::Imm16,      3,   opcode_ld),
    /* 0x22 LD [HL+] A   | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x23 INC HL       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_inc),
    /* 0x24 INC H        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x25 DEC H        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x26 LD H n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x27 DAA          | Z - 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_daa),
    /* 0x28 JR Z e8      | - - - - */  Instruction(OperandKind::Flag_Z,     OperandKind::Imm8,       3,   opcode_jr),
    /* 0x29 ADD HL HL    | - 0 H C */  Instruction(OperandKind::R16,        OperandKind::R16,        2,   opcode_add),
    /* 0x2A LD A [HL+]   | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x2B DEC HL       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_dec),
    /* 0x2C INC L        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x2D DEC L        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x2E LD L n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x2F CPL          | - 1 1 - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_cpl),
    /* 0x30 JR NC e8     | - - - - */  Instruction(OperandKind::Flag_NC,    OperandKind::Imm8,       3,   opcode_jr),
    /* 0x31 LD SP n16    | - - - - */  Instruction(OperandKind::R16,        OperandKind::Imm16,      3,   opcode_ld),
    /* 0x32 LD [HL-] A   | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x33 INC SP       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_inc),
    /* 0x34 INC [HL]     | Z 0 H - */  Instruction(OperandKind::R16_Addr,   OperandKind::None,       3,   opcode_inc),
    /* 0x35 DEC [HL]     | Z 1 H - */  Instruction(OperandKind::R16_Addr,   OperandKind::None,       3,   opcode_dec),
    /* 0x36 LD [HL] n8   | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::Imm8,       3,   opcode_ld),
    /* 0x37 SCF          | - 0 0 1 */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_scf),
    /* 0x38 JR C e8      | - - - - */  Instruction(OperandKind::Flag_C,     OperandKind::Imm8,       3,   opcode_jr),
    /* 0x39 ADD HL SP    | - 0 H C */  Instruction(OperandKind::R16,        OperandKind::R16,        2,   opcode_add),
    /* 0x3A LD A [HL-]   | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x3B DEC SP       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       2,   opcode_dec),
    /* 0x3C INC A        | Z 0 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_inc),
    /* 0x3D DEC A        | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::None,       1,   opcode_dec),
    /* 0x3E LD A n8      | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_ld),
    /* 0x3F CCF          | - 0 0 C */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_ccf),
    /* 0x40 LD B B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x41 LD B C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x42 LD B D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x43 LD B E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x44 LD B H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x45 LD B L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x46 LD B [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x47 LD B A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x48 LD C B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x49 LD C C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x4A LD C D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x4B LD C E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x4C LD C H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x4D LD C L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x4E LD C [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x4F LD C A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x50 LD D B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x51 LD D C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x52 LD D D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x53 LD D E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x54 LD D H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x55 LD D L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x56 LD D [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x57 LD D A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x58 LD E B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x59 LD E C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x5A LD E D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x5B LD E E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x5C LD E H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x5D LD E L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x5E LD E [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x5F LD E A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x60 LD H B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x61 LD H C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x62 LD H D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x63 LD H E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x64 LD H H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x65 LD H L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x66 LD H [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x67 LD H A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x68 LD L B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x69 LD L C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x6A LD L D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x6B LD L E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x6C LD L H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x6D LD L L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x6E LD L [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x6F LD L A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x70 LD [HL] B    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x71 LD [HL] C    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x72 LD [HL] D    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x73 LD [HL] E    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x74 LD [HL] H    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x75 LD [HL] L    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x76 HALT         | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_halt),
    /* 0x77 LD [HL] A    | - - - - */  Instruction(OperandKind::R16_Addr,   OperandKind::R8,         2,   opcode_ld),
    /* 0x78 LD A B       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x79 LD A C       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x7A LD A D       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x7B LD A E       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x7C LD A H       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x7D LD A L       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x7E LD A [HL]    | - - - - */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_ld),
    /* 0x7F LD A A       | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_ld),
    /* 0x80 ADD A B      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x81 ADD A C      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x82 ADD A D      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x83 ADD A E      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x84 ADD A H      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x85 ADD A L      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x86 ADD A [HL]   | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_add),
    /* 0x87 ADD A A      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_add),
    /* 0x88 ADC A B      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x89 ADC A C      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x8A ADC A D      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x8B ADC A E      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x8C ADC A H      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x8D ADC A L      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x8E ADC A [HL]   | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_adc),
    /* 0x8F ADC A A      | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_adc),
    /* 0x90 SUB A B      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x91 SUB A C      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x92 SUB A D      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x93 SUB A E      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x94 SUB A H      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x95 SUB A L      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x96 SUB A [HL]   | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_sub),
    /* 0x97 SUB A A      | 1 1 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sub),
    /* 0x98 SBC A B      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x99 SBC A C      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x9A SBC A D      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x9B SBC A E      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x9C SBC A H      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x9D SBC A L      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0x9E SBC A [HL]   | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_sbc),
    /* 0x9F SBC A A      | Z 1 H - */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_sbc),
    /* 0xA0 AND A B      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA1 AND A C      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA2 AND A D      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA3 AND A E      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA4 AND A H      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA5 AND A L      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA6 AND A [HL]   | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_and),
    /* 0xA7 AND A A      | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_and),
    /* 0xA8 XOR A B      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xA9 XOR A C      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xAA XOR A D      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xAB XOR A E      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xAC XOR A H      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xAD XOR A L      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xAE XOR A [HL]   | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_xor),
    /* 0xAF XOR A A      | 1 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_xor),
    /* 0xB0 OR A B       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB1 OR A C       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB2 OR A D       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB3 OR A E       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB4 OR A H       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB5 OR A L       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB6 OR A [HL]    | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_or),
    /* 0xB7 OR A A       | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_or),
    /* 0xB8 CP A B       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xB9 CP A C       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xBA CP A D       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xBB CP A E       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xBC CP A H       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xBD CP A L       | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xBE CP A [HL]    | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::R16_Addr,   2,   opcode_cp),
    /* 0xBF CP A A       | 1 1 0 0 */  Instruction(OperandKind::R8,         OperandKind::R8,         1,   opcode_cp),
    /* 0xC0 RET NZ       | - - - - */  Instruction(OperandKind::Flag_NZ,    OperandKind::None,       5,   opcode_ret),
    /* 0xC1 POP BC       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       3,   opcode_pop),
    /* 0xC2 JP NZ a16    | - - - - */  Instruction(OperandKind::Flag_NZ,    OperandKind::Imm16_Addr, 4,   opcode_jp),
    /* 0xC3 JP a16       | - - - - */  Instruction(OperandKind::Imm16_Addr, OperandKind::None,       4,   opcode_jp),
    /* 0xC4 CALL NZ a16  | - - - - */  Instruction(OperandKind::Flag_NZ,    OperandKind::Imm16_Addr, 6,   opcode_call),
    /* 0xC5 PUSH BC      | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       4,   opcode_push),
    /* 0xC6 ADD A n8     | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_add),
    /* 0xC7 RST $00      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xC8 RET Z        | - - - - */  Instruction(OperandKind::Flag_Z,     OperandKind::None,       5,   opcode_ret),
    /* 0xC9 RET          | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_ret),
    /* 0xCA JP Z a16     | - - - - */  Instruction(OperandKind::Flag_Z,     OperandKind::Imm16_Addr, 4,   opcode_jp),
    /* 0xCB PREFIX       | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_prefix),
    /* 0xCC CALL Z a16   | - - - - */  Instruction(OperandKind::Flag_Z,     OperandKind::Imm16_Addr, 6,   opcode_call),
    /* 0xCD CALL a16     | - - - - */  Instruction(OperandKind::Imm16_Addr, OperandKind::None,       6,   opcode_call),
    /* 0xCE ADC A n8     | Z 0 H C */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_adc),
    /* 0xCF RST $08      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xD0 RET NC       | - - - - */  Instruction(OperandKind::Flag_NC,    OperandKind::None,       5,   opcode_ret),
    /* 0xD1 POP DE       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       3,   opcode_pop),
    /* 0xD2 JP NC a16    | - - - - */  Instruction(OperandKind::Flag_NC,    OperandKind::Imm16_Addr, 4,   opcode_jp),
    /* 0xD3 ILLEGAL_D3   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_d3),
    /* 0xD4 CALL NC a16  | - - - - */  Instruction(OperandKind::Flag_NC,    OperandKind::Imm16_Addr, 6,   opcode_call),
    /* 0xD5 PUSH DE      | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       4,   opcode_push),
    /* 0xD6 SUB A n8     | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_sub),
    /* 0xD7 RST $10      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xD8 RET C        | - - - - */  Instruction(OperandKind::Flag_C,     OperandKind::None,       5,   opcode_ret),
    /* 0xD9 RETI         | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_reti),
    /* 0xDA JP C a16     | - - - - */  Instruction(OperandKind::Flag_C,     OperandKind::Imm16_Addr, 4,   opcode_jp),
    /* 0xDB ILLEGAL_DB   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_db),
    /* 0xDC CALL C a16   | - - - - */  Instruction(OperandKind::Flag_C,     OperandKind::Imm16_Addr, 6,   opcode_call),
    /* 0xDD ILLEGAL_DD   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_dd),
    /* 0xDE SBC A n8     | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_sbc),
    /* 0xDF RST $18      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xE0 LDH [a8] A   | - - - - */  Instruction(OperandKind::Imm8_Addr,  OperandKind::R8,         3,   opcode_ldh),
    /* 0xE1 POP HL       | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       3,   opcode_pop),
    /* 0xE2 LD [C] A     | - - - - */  Instruction(OperandKind::R8_Addr,    OperandKind::R8,         2,   opcode_ld),
    /* 0xE3 ILLEGAL_E3   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_e3),
    /* 0xE4 ILLEGAL_E4   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_e4),
    /* 0xE5 PUSH HL      | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       4,   opcode_push),
    /* 0xE6 AND A n8     | Z 0 1 0 */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_and),
    /* 0xE7 RST $20      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xE8 ADD SP e8    | 0 0 H C */  Instruction(OperandKind::R16,        OperandKind::Imm8,       4,   opcode_add),
    /* 0xE9 JP HL        | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       1,   opcode_jp),
    /* 0xEA LD [a16] A   | - - - - */  Instruction(OperandKind::Imm16_Addr, OperandKind::R8,         4,   opcode_ld),
    /* 0xEB ILLEGAL_EB   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_eb),
    /* 0xEC ILLEGAL_EC   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_ec),
    /* 0xED ILLEGAL_ED   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_ed),
    /* 0xEE XOR A n8     | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_xor),
    /* 0xEF RST $28      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xF0 LDH A [a8]   | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm8_Addr,  3,   opcode_ldh),
    /* 0xF1 POP AF       | Z N H C */  Instruction(OperandKind::R16,        OperandKind::None,       3,   opcode_pop),
    /* 0xF2 LD A [C]     | - - - - */  Instruction(OperandKind::R8,         OperandKind::R8_Addr,    2,   opcode_ld),
    /* 0xF3 DI           | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_di),
    /* 0xF4 ILLEGAL_F4   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_f4),
    /* 0xF5 PUSH AF      | - - - - */  Instruction(OperandKind::R16,        OperandKind::None,       4,   opcode_push),
    /* 0xF6 OR A n8      | Z 0 0 0 */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_or),
    /* 0xF7 RST $30      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
    /* 0xF8 LD HL SP+    | 0 0 H C */  Instruction(OperandKind::R16,        OperandKind::R16,        3,   opcode_ld),
    /* 0xF9 LD SP HL     | - - - - */  Instruction(OperandKind::R16,        OperandKind::R16,        2,   opcode_ld),
    /* 0xFA LD A [a16]   | - - - - */  Instruction(OperandKind::R8,         OperandKind::Imm16_Addr, 4,   opcode_ld),
    /* 0xFB EI           | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_ei),
    /* 0xFC ILLEGAL_FC   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_fc),
    /* 0xFD ILLEGAL_FD   | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       1,   opcode_illegal_fd),
    /* 0xFE CP A n8      | Z 1 H C */  Instruction(OperandKind::R8,         OperandKind::Imm8,       2,   opcode_cp),
    /* 0xFF RST $38      | - - - - */  Instruction(OperandKind::None,       OperandKind::None,       4,   opcode_rst),
];