use crate::emu::emu::Emu;

use super::inst_impl::*;

#[derive(Debug, Clone, Copy)]
pub enum OperandKind {
    /* implied */                   None,
    /* 8 bit register */            R8,
    /* 16 bit register */           R16,
    /* 8 bit immediate */           Imm8,
    /* 16 bit immediate */          Imm16,
    /* 8 bit register address */    R8Addr,
    /* 16 bit register address */   R16Addr,
    /* 8 bit immediate address */   Imm8Addr,
    /* 16 bit immediate address */  Imm16Addr,
    FlagNZ,
    FlagZ,
    FlagNC,
    FlagC,
}

pub struct Instruction {
    pub dst: OperandKind,
    pub src: OperandKind,
    pub cycles: u8,
    pub cycles_skipped: u8,
    pub exec: fn(emu: &mut Emu, instr: &Instruction, opcode: u8),
}

pub fn get_instruction(opcode: u8) -> &'static Instruction {
    return &INSTR_INDEX[usize::from(opcode)];
}

// https://gbdev.io/gb-opcodes/optables/
const INSTR_INDEX: [Instruction; 256] = [
/* 0x00 NOP          | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_nop},
/* 0x01 LD BC n16    | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::Imm16,      cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0x02 LD [BC] A    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x03 INC BC       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_inc},
/* 0x04 INC B        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x05 DEC B        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x06 LD B n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x07 RLCA         | 0 0 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_rlca},
/* 0x08 LD [a16] SP  | - - - - */  Instruction{dst:OperandKind::Imm16Addr,  src:OperandKind::R16,        cycles:5,   cycles_skipped:0,   exec:opcode_ld},
/* 0x09 ADD HL BC    | - 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0x0A LD A [BC]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x0B DEC BC       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_dec},
/* 0x0C INC C        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x0D DEC C        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x0E LD C n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x0F RRCA         | 0 0 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_rrca},
/* 0x10 STOP n8      | - - - - */  Instruction{dst:OperandKind::Imm8,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_stop},
/* 0x11 LD DE n16    | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::Imm16,      cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0x12 LD [DE] A    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x13 INC DE       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_inc},
/* 0x14 INC D        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x15 DEC D        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x16 LD D n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x17 RLA          | 0 0 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_rla},
/* 0x18 JR e8        | - - - - */  Instruction{dst:OperandKind::Imm8,       src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_jr},
/* 0x19 ADD HL DE    | - 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0x1A LD A [DE]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x1B DEC DE       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_dec},
/* 0x1C INC E        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x1D DEC E        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x1E LD E n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x1F RRA          | 0 0 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_rra},
/* 0x20 JR NZ e8     | - - - - */  Instruction{dst:OperandKind::FlagNZ,     src:OperandKind::Imm8,       cycles:3,   cycles_skipped:2,   exec:opcode_jr},
/* 0x21 LD HL n16    | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::Imm16,      cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0x22 LD [HL+] A   | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x23 INC HL       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_inc},
/* 0x24 INC H        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x25 DEC H        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x26 LD H n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x27 DAA          | Z - 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_daa},
/* 0x28 JR Z e8      | - - - - */  Instruction{dst:OperandKind::FlagZ,      src:OperandKind::Imm8,       cycles:3,   cycles_skipped:2,   exec:opcode_jr},
/* 0x29 ADD HL HL    | - 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0x2A LD A [HL+]   | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x2B DEC HL       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_dec},
/* 0x2C INC L        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x2D DEC L        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x2E LD L n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x2F CPL          | - 1 1 - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_cpl},
/* 0x30 JR NC e8     | - - - - */  Instruction{dst:OperandKind::FlagNC,     src:OperandKind::Imm8,       cycles:3,   cycles_skipped:2,   exec:opcode_jr},
/* 0x31 LD SP n16    | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::Imm16,      cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0x32 LD [HL-] A   | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x33 INC SP       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_inc},
/* 0x34 INC [HL]     | Z 0 H - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_inc},
/* 0x35 DEC [HL]     | Z 1 H - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_dec},
/* 0x36 LD [HL] n8   | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::Imm8,       cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0x37 SCF          | - 0 0 1 */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_scf},
/* 0x38 JR C e8      | - - - - */  Instruction{dst:OperandKind::FlagC,      src:OperandKind::Imm8,       cycles:3,   cycles_skipped:2,   exec:opcode_jr},
/* 0x39 ADD HL SP    | - 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0x3A LD A [HL-]   | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x3B DEC SP       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:2,   cycles_skipped:0,   exec:opcode_dec},
/* 0x3C INC A        | Z 0 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_inc},
/* 0x3D DEC A        | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_dec},
/* 0x3E LD A n8      | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x3F CCF          | - 0 0 C */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_ccf},
/* 0x40 LD B B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x41 LD B C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x42 LD B D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x43 LD B E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x44 LD B H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x45 LD B L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x46 LD B [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x47 LD B A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x48 LD C B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x49 LD C C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4A LD C D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4B LD C E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4C LD C H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4D LD C L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4E LD C [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x4F LD C A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x50 LD D B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x51 LD D C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x52 LD D D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x53 LD D E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x54 LD D H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x55 LD D L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x56 LD D [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x57 LD D A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x58 LD E B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x59 LD E C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5A LD E D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5B LD E E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5C LD E H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5D LD E L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5E LD E [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x5F LD E A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x60 LD H B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x61 LD H C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x62 LD H D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x63 LD H E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x64 LD H H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x65 LD H L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x66 LD H [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x67 LD H A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x68 LD L B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x69 LD L C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6A LD L D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6B LD L E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6C LD L H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6D LD L L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6E LD L [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x6F LD L A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x70 LD [HL] B    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x71 LD [HL] C    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x72 LD [HL] D    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x73 LD [HL] E    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x74 LD [HL] H    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x75 LD [HL] L    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x76 HALT         | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_halt},
/* 0x77 LD [HL] A    | - - - - */  Instruction{dst:OperandKind::R16Addr,    src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x78 LD A B       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x79 LD A C       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7A LD A D       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7B LD A E       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7C LD A H       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7D LD A L       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7E LD A [HL]    | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0x7F LD A A       | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_ld},
/* 0x80 ADD A B      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x81 ADD A C      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x82 ADD A D      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x83 ADD A E      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x84 ADD A H      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x85 ADD A L      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x86 ADD A [HL]   | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0x87 ADD A A      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_add},
/* 0x88 ADC A B      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x89 ADC A C      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8A ADC A D      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8B ADC A E      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8C ADC A H      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8D ADC A L      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8E ADC A [HL]   | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_adc},
/* 0x8F ADC A A      | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_adc},
/* 0x90 SUB A B      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x91 SUB A C      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x92 SUB A D      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x93 SUB A E      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x94 SUB A H      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x95 SUB A L      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x96 SUB A [HL]   | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_sub},
/* 0x97 SUB A A      | 1 1 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sub},
/* 0x98 SBC A B      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x99 SBC A C      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9A SBC A D      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9B SBC A E      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9C SBC A H      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9D SBC A L      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9E SBC A [HL]   | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_sbc},
/* 0x9F SBC A A      | Z 1 H - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_sbc},
/* 0xA0 AND A B      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA1 AND A C      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA2 AND A D      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA3 AND A E      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA4 AND A H      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA5 AND A L      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA6 AND A [HL]   | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_and},
/* 0xA7 AND A A      | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_and},
/* 0xA8 XOR A B      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xA9 XOR A C      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAA XOR A D      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAB XOR A E      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAC XOR A H      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAD XOR A L      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAE XOR A [HL]   | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_xor},
/* 0xAF XOR A A      | 1 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_xor},
/* 0xB0 OR A B       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB1 OR A C       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB2 OR A D       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB3 OR A E       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB4 OR A H       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB5 OR A L       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB6 OR A [HL]    | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_or},
/* 0xB7 OR A A       | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_or},
/* 0xB8 CP A B       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xB9 CP A C       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBA CP A D       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBB CP A E       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBC CP A H       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBD CP A L       | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBE CP A [HL]    | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::R16Addr,    cycles:2,   cycles_skipped:0,   exec:opcode_cp},
/* 0xBF CP A A       | 1 1 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8,         cycles:1,   cycles_skipped:0,   exec:opcode_cp},
/* 0xC0 RET NZ       | - - - - */  Instruction{dst:OperandKind::FlagNZ,     src:OperandKind::None,       cycles:5,   cycles_skipped:2,   exec:opcode_ret},
/* 0xC1 POP BC       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_pop},
/* 0xC2 JP NZ a16    | - - - - */  Instruction{dst:OperandKind::FlagNZ,     src:OperandKind::Imm16Addr,  cycles:4,   cycles_skipped:3,   exec:opcode_jp},
/* 0xC3 JP a16       | - - - - */  Instruction{dst:OperandKind::Imm16Addr,  src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_jp},
/* 0xC4 CALL NZ a16  | - - - - */  Instruction{dst:OperandKind::FlagNZ,     src:OperandKind::Imm16Addr,  cycles:6,   cycles_skipped:3,   exec:opcode_call},
/* 0xC5 PUSH BC      | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_push},
/* 0xC6 ADD A n8     | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_add},
/* 0xC7 RST $00      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xC8 RET Z        | - - - - */  Instruction{dst:OperandKind::FlagZ,      src:OperandKind::None,       cycles:5,   cycles_skipped:2,   exec:opcode_ret},
/* 0xC9 RET          | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_ret},
/* 0xCA JP Z a16     | - - - - */  Instruction{dst:OperandKind::FlagZ,      src:OperandKind::Imm16Addr,  cycles:4,   cycles_skipped:3,   exec:opcode_jp},
/* 0xCB PREFIX       | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_prefix},
/* 0xCC CALL Z a16   | - - - - */  Instruction{dst:OperandKind::FlagZ,      src:OperandKind::Imm16Addr,  cycles:6,   cycles_skipped:3,   exec:opcode_call},
/* 0xCD CALL a16     | - - - - */  Instruction{dst:OperandKind::Imm16Addr,  src:OperandKind::None,       cycles:6,   cycles_skipped:0,   exec:opcode_call},
/* 0xCE ADC A n8     | Z 0 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_adc},
/* 0xCF RST $08      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xD0 RET NC       | - - - - */  Instruction{dst:OperandKind::FlagNC,     src:OperandKind::None,       cycles:5,   cycles_skipped:2,   exec:opcode_ret},
/* 0xD1 POP DE       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_pop},
/* 0xD2 JP NC a16    | - - - - */  Instruction{dst:OperandKind::FlagNC,     src:OperandKind::Imm16Addr,  cycles:4,   cycles_skipped:3,   exec:opcode_jp},
/* 0xD3 ILLEGAL_D3   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_d3},
/* 0xD4 CALL NC a16  | - - - - */  Instruction{dst:OperandKind::FlagNC,     src:OperandKind::Imm16Addr,  cycles:6,   cycles_skipped:3,   exec:opcode_call},
/* 0xD5 PUSH DE      | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_push},
/* 0xD6 SUB A n8     | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_sub},
/* 0xD7 RST $10      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xD8 RET C        | - - - - */  Instruction{dst:OperandKind::FlagC,      src:OperandKind::None,       cycles:5,   cycles_skipped:2,   exec:opcode_ret},
/* 0xD9 RETI         | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_reti},
/* 0xDA JP C a16     | - - - - */  Instruction{dst:OperandKind::FlagC,      src:OperandKind::Imm16Addr,  cycles:4,   cycles_skipped:3,   exec:opcode_jp},
/* 0xDB ILLEGAL_DB   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_db},
/* 0xDC CALL C a16   | - - - - */  Instruction{dst:OperandKind::FlagC,      src:OperandKind::Imm16Addr,  cycles:6,   cycles_skipped:3,   exec:opcode_call},
/* 0xDD ILLEGAL_DD   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_dd},
/* 0xDE SBC A n8     | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_sbc},
/* 0xDF RST $18      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xE0 LDH [a8] A   | - - - - */  Instruction{dst:OperandKind::Imm8Addr,   src:OperandKind::R8,         cycles:3,   cycles_skipped:0,   exec:opcode_ldh},
/* 0xE1 POP HL       | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_pop},
/* 0xE2 LD [C] A     | - - - - */  Instruction{dst:OperandKind::R8Addr,     src:OperandKind::R8,         cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0xE3 ILLEGAL_E3   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_e3},
/* 0xE4 ILLEGAL_E4   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_e4},
/* 0xE5 PUSH HL      | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_push},
/* 0xE6 AND A n8     | Z 0 1 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_and},
/* 0xE7 RST $20      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xE8 ADD SP e8    | 0 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::Imm8,       cycles:4,   cycles_skipped:0,   exec:opcode_add},
/* 0xE9 JP HL        | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_jp},
/* 0xEA LD [a16] A   | - - - - */  Instruction{dst:OperandKind::Imm16Addr,  src:OperandKind::R8,         cycles:4,   cycles_skipped:0,   exec:opcode_ld},
/* 0xEB ILLEGAL_EB   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_eb},
/* 0xEC ILLEGAL_EC   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_ec},
/* 0xED ILLEGAL_ED   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_ed},
/* 0xEE XOR A n8     | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_xor},
/* 0xEF RST $28      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xF0 LDH A [a8]   | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8Addr,   cycles:3,   cycles_skipped:0,   exec:opcode_ldh},
/* 0xF1 POP AF       | Z N H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:3,   cycles_skipped:0,   exec:opcode_pop},
/* 0xF2 LD A [C]     | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::R8Addr,     cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0xF3 DI           | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_di},
/* 0xF4 ILLEGAL_F4   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_f4},
/* 0xF5 PUSH AF      | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_push},
/* 0xF6 OR A n8      | Z 0 0 0 */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_or},
/* 0xF7 RST $30      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
/* 0xF8 LD HL SP+    | 0 0 H C */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:3,   cycles_skipped:0,   exec:opcode_ld},
/* 0xF9 LD SP HL     | - - - - */  Instruction{dst:OperandKind::R16,        src:OperandKind::R16,        cycles:2,   cycles_skipped:0,   exec:opcode_ld},
/* 0xFA LD A [a16]   | - - - - */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm16Addr,  cycles:4,   cycles_skipped:0,   exec:opcode_ld},
/* 0xFB EI           | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_ei},
/* 0xFC ILLEGAL_FC   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_fc},
/* 0xFD ILLEGAL_FD   | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:1,   cycles_skipped:0,   exec:opcode_illegal_fd},
/* 0xFE CP A n8      | Z 1 H C */  Instruction{dst:OperandKind::R8,         src:OperandKind::Imm8,       cycles:2,   cycles_skipped:0,   exec:opcode_cp},
/* 0xFF RST $38      | - - - - */  Instruction{dst:OperandKind::None,       src:OperandKind::None,       cycles:4,   cycles_skipped:0,   exec:opcode_rst},
];
